export const INCREMENT_COUNTER_SYNC = 'INCREMENT_COUNTER_SYNC';
export type INCREMENT_COUNTER_SYNC = typeof INCREMENT_COUNTER_SYNC;

export const DECREMENT_COUNTER_SYNC = 'DECREMENT_COUNTER_SYNC';
export type DECREMENT_COUNTER_SYNC = typeof DECREMENT_COUNTER_SYNC;

export const INCREMENT_COUNTER_ASYNC = 'INCREMENT_COUNTER_ASYNC';
export type INCREMENT_COUNTER_ASYNC = typeof INCREMENT_COUNTER_ASYNC;

export const DECREMENT_COUNTER_ASYNC = 'DECREMENT_COUNTER_ASYNC';
export type DECREMENT_COUNTER_ASYNC = typeof DECREMENT_COUNTER_ASYNC;